Fix errors in README
OneDrive/onedrive-data-robot-azure-function pull request #1
Opened 2017-06-22 23:07 UTC by jisungk

- add information about updating the connection string information
- update keyword to correct one: `!odbot`
- fix bad links and style errors

2017-06-22 23:07 UTC, msftclas commented
This seems like a small (but important) contribution, so no Contribution License Agreement is required at this point. We will now review your pull request.
_Thanks,
Microsoft Pull Request Bot_

2017-07-17 20:34 UTC, rgregg requested changes
Just minor tweaks that need to be made before I can merge this in.

2017-07-17 20:34 UTC, rgregg commented on README.md
> +    * In the [`Web.config`](https://github.com/jisungk/onedrive-data-robot-azure-function/blob/jisungk-edits/OneDriveDataRobot/Web.config) file on the line: `<add key="ida:ClientId" value="[ClientId]
Can you make these links relative links so they don't break when this code is integrated into the original project?

2017-07-17 20:34 UTC, rgregg commented on README.md
> +3. Copy the code from [`run.csx`](https://github.com/OneDrive/onedrive-data-robot-azure-function/blob/master/AzureFunction/run.csx) and paste it into the code editor and then click **Save**.
Another place for a relative link.

2017-07-17 20:34 UTC, rgregg commented on README.md
> +10. Navigate to the [Azure Portal](https://ms.portal.azure.com) and go to **Storage Accounts** on the left-hand navigation bar.
Need to remove the ms. from this URL

2017-07-17 21:32 UTC, jisungk commented
I implemented the suggested changes in the latest commit, 7d141c5!

2017-08-07 18:18 UTC, rgregg approved these changes

2017-08-07 18:18 UTC, merged